import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '../components/organisms/Navbar';
import Footer from '../components/molecules/footer.module';
import ClientProviders from '../components/atoms/ClientProviders';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from '@/components/ui/sonner';
import NavigationLoader from '../components/atoms/NavigationLoader';
import { SpeedInsights } from '@vercel/speed-insights/next';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <SessionProvider>
          <ClientProviders>
            {/* Fixed header with proper z-index */}
            <header className="sticky top-0 z-50 w-full">
              <Navbar />
            </header>
            
            {/* Main content with flex-grow to push footer down */}
            <main className="flex-grow">{children}</main>
            
            <Footer />
            
            {/* Navigation loading indicator */}
            <NavigationLoader />
            
            {/* Sonner toaster */}
            <Toaster />
          </ClientProviders>
        </SessionProvider>

        {/* Vercel Speed Insights */}
        <SpeedInsights />
      </body>
    </html>
  );
}